### ISSUE TITLE
Module submission: 3c system helper

### ISSUE THREAD

**Issue by Efreak** [topjohnwu/Magisk_Repo_Submissions#156]
The repo is at [Efreak/3c-system-helper-magisk](https://github.com/Efreak/3c-system-helper-magisk).

This adds the 3c system helper apk to the /system/priv-app folder.

For more information on the system helper, see [here](https://www.3c71.com/android/?q=node/922).

If this is accepted, please let me know instead of forking--I would prefer to [transfer](https://help.github.com/articles/about-repository-transfers/) the repo to you.

**Comment by topjohnwu** [comment]
I will not fork your repo to the Github organization. I will create a new repo, clone your repo using Github's native implementation, and add you as a collaborator. I think this is 99% the same as transferring a repo, plus you can still edit the repo!

BTW for your information, I **cannot** fork your repo to my organization, since each owner can only have one single fork of the same repo. The only way is to use cloning

Either you insist to use transfer, or allow me to clone your repo for you, let me know :)

**Comment by Efreak** [comment]
Either one is honestly fine with me. The transfer is preferable as it keeps
the release .zip and I can delete the repo without losing links, but it's
not a big deal.
Efreak <https://github.com/Efreak>

**Comment by topjohnwu** [comment]
Bad Request: Your [submission link](https://github.com/Efreak/3c-system-helper-magisk)) is not a valid Magisk Module!
Reason: `module.prop` does not exist on `master` branch
