### ISSUE TITLE
[Module submission] Systemless Substratum Legacy

### ISSUE THREAD

**Issue by TheComputerGuy96** [topjohnwu/Magisk_Repo_Submissions#184]
https://github.com/TheComputerGuy96/systemless-substratum-legacy

Allows systemless installation of Substratum themes when a ROM doesn't support OMS (Legacy/Root mode)

Note: Please add @Nodens- as a collaborator as well, because he's the author of this module

**Comment by topjohnwu** [comment]
New repo added: [systemless-substratum-legacy](https://github.com/Magisk-Modules-Repo/systemless-substratum-legacy), please accept the collaboration invitation in your email

**Comment by Nodens-** [comment]
@topjohnwu: Came back to the city and was just set out to work on this when I saw @TheComputerGuy96 has ported the template version changes on his fork but instead of doing a PR to my repo so I can accept it and add it to the magisk repos myself he added it himself which basically has locked me out of my module as I don't have collaborator access... Considering you have automated the repo submission process, I hope you can see this post so you can add me as collaborator.

 As a sidenote, the Magisk repo design is not very efficient. The way it is being done, control of the repos is transferred to you which means you would have to micromanage stuff like this and also limit what we can do with our repos (eg if I want to add another collaborator I would have to pester you again etc).
As the amount of modules/repos grows this will become impossible to maintain.
 Instead, you should just pull files from our original repos and just maintain a list of them that magic manager uses. This current design is encumbering you and prevents us from full control of our repos.

**Comment by TheComputerGuy96** [comment]
@Nodens- Just increased your collaborator access to Admin, let me know if you'd like to own this repository
