### ISSUE TITLE
[Submission] Camera Mi5s improvements

### ISSUE THREAD

**Issue by WaveGenerator** [topjohnwu/Magisk_Repo_Submissions#325]
https://github.com/WaveGenerator/Camera-Mi5s-improvements/tree/master

**Comment by Didgeridoohan** [comment]
Just a heads up:
You're using the 1400 template that no longer works from Magisk v16.3. It's advisable to always use the latest template (currently 1500).

**Comment by WaveGenerator** [comment]
done

**Comment by Didgeridoohan** [comment]
Nope...

It's not enough to just change the version number. There's a whole lot going on in the background as well.

Try again.

**Comment by WaveGenerator** [comment]
it's simple files replacing, would it be better for compability for users with older Magisk?

**Comment by Didgeridoohan** [comment]
The issue is that you've used the 1400 template when creating your module, and when you then uploaded your files to GitHub you overwrote the code for the 1500 template. This module will "only" install on Magisk v14.0 to v16.2.

It's of course up to you, but I would start over with the 1500 template (https://github.com/topjohnwu/magisk-module-template), especially since you're submitting it to the Magisk repo. It's quite likely that template 1400 modules won't show in the Manager Downloads after the next stable release...

If you want to keep compatibility with Magisk v14 you could keep a template 1400 version for download somewhere else (support thread).

**Comment by WaveGenerator** [comment]
thank you for explanation, replace update-binary from 1500 template and change module.prop, so, it must be fully compatible to 1500 now

**Comment by topjohnwu** [comment]
New repo added: [Camera-Mi5s-improvements](https://github.com/Magisk-Modules-Repo/Camera-Mi5s-improvements), please accept the collaboration invitation in your email
